/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Applique: typeof import('./src/components/Pages/Creation/Applique.vue')['default']
    AuthorizationPage: typeof import('./src/components/Pages/Authorization/AuthorizationPage.vue')['default']
    BaseFooter: typeof import('./src/components/Layouts/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/Layouts/BaseHeader.vue')['default']
    Creation: typeof import('./src/components/Pages/Creation/Creation.vue')['default']
    Drawing: typeof import('./src/components/Pages/Creation/Drawing.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    GalleryPage: typeof import('./src/components/Pages/Gallery/GalleryPage.vue')['default']
    Home: typeof import('./src/components/Pages/Home/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LeftMenu: typeof import('./src/components/Layouts/LeftMenu.vue')['default']
    LoginPage: typeof import('./src/components/Pages/LoginPage.vue')['default']
    MainHeader: typeof import('./src/components/Layouts/MainHeader.vue')['default']
    Neuropsychology: typeof import('./src/components/Pages/Neuropsychology/Neuropsychology.vue')['default']
    Psychology: typeof import('./src/components/Pages/Psychology/Psychology.vue')['default']
    RegistrationPage: typeof import('./src/components/Pages/RegistrationPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/UiComponents/SideBar/SideBar.vue')['default']
    SidebarItem: typeof import('./src/components/UiComponents/SideBar/SidebarItem.vue')['default']
    SimpleCard: typeof import('./src/components/UiComponents/Cards/SimpleCard.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Tutorial: typeof import('./src/components/Pages/Tutorial/Tutorial.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
